### ISSUE TITLE
Don't mandate remote section

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#102]
When dfetch is used for a project with only 1 project, the remote sections is useless overhead. Following should be possible

```yaml
            manifest:
              version: '0.0'

              projects:
                - name: ext/test-repo-tag
                  url: https://github.com/dfetch-org/test-repo
                  tag: v1
```
