### ISSUE TITLE
Import doesn't parse all externals in svn

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#133]
When using `dfetch -v import` following svn output is shown, but the `Core\FileSystem\Resources` are not in the manifest.

```console
Core\FileSystem\Resources - ^/DATA-MYPROJECT-SOME-FILES SomeFiles
^/DATA-MYPROJECT-SOME-OTHER-FILES/Processed SomeOtherFiles

Core\Legacy\Info - ^/DOCS-MYPROJECT/Build/trunk/Build.md@6128 Build.md

Core\Legacy\Info\guides - ^/DOCS-MYPROJECT/Filesystem/trunk@6128 Filesystem
^/DOCS-MYPROJECT/SomeOtherFiles/trunk@6128 SomeOtherFiles

Quality - http://svn.mycompany.com/MYCOMPANY/Jenkins/Project/Resources/tags/0.1.0@592 Resources

Tests\functional - http://svn.mycompany.com/MYCOMPANY/SomeFramework/tags/v0.1.15/PythonPackage/dist@597 SomeFramework

```

```yaml
manifest:
  version: '0.0'
  
  remotes:
  - name: svn-mycompany-com-PD28-DOCS-SOMEPROJECT
    url-base: http://svn.mycompany.com/PD28/DOCS-SOMEPROJECT
    
  - name: svn-mycompany-com-MYCOMPANY-Jenkins-Project
    url-base: http://svn.mycompany.com/MYCOMPANY/Jenkins/Project
    
  - name: svn-mycompany-com-MYCOMPANY
    url-base: http://svn.mycompany.com/MYCOMPANY
    
  projects:
  - name: Build.md
    revision: '6128'
    remote: svn-mycompany-com-PD28-DOCS-SOMEPROJECT
    src: Build.md
    dst: Core/Legacy/Info/Build.md
    repo-path: Build
    
  - name: Filesystem
    revision: '6128'
    remote: svn-mycompany-com-PD28-DOCS-SOMEPROJECT
    dst: Core/Legacy/Info/guides/Filesystem
    repo-path: Filesystem
    
  - name: SomeOtherFiles
    revision: '6128'
    remote: svn-mycompany-com-PD28-DOCS-SOMEPROJECT
    dst: Core/Legacy/Info/guides/SomeOtherFiles
    repo-path: SomeOtherFiles
    
  - name: Resources
    revision: '592'
    remote: svn-mycompany-com-MYCOMPANY-Jenkins-Project
    dst: Quality/Resources
    tag: 0.1.0
    repo-path: Resources
    
  - name: SomeFramework
    revision: '597'
    remote: svn-mycompany-com-MYCOMPANY
    src: PythonPackage/dist
    dst: Tests/functional/SomeFramework
    tag: v0.1.15
    repo-path: SomeFramework
```
