### ISSUE TITLE
Warn user to not change metadata

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#170]
DFetch generates a dfetch_data.yaml for each fetched project.
Add a comment line as first line in the file when dumping it: https://github.com/dfetch-org/dfetch/blob/main/dfetch/project/metadata.py#L132

```yaml
# This is a generated file by dfetch. Don't edit this, but edit the manifest. 
# For more info see https://dfetch.readthedocs.io/en/latest/getting_started.html
dfetch:
  branch: master
  hash: 91e1879aa7b4ff7a76827611e3d9ff5d
```
