### ISSUE TITLE
Use dfetch for tracking upstream template

### ISSUE THREAD

**Issue by spoorcc** [dfetch-org/dfetch#334]
Some projects are based off off other "template" projects. 

## Template
- `somefolder`
  - `someFile`
- `.someconfig`
- `README.md`

## Child project
- `someotherfolder`
  - `someFile`
- `somefolder`
  - `someFile`
- `.someconfig`
- `README.md` (own README)
- `dfetch.yaml`

It would be nice if a user could have a child project based off off certain parts of a parent template project.
In above example `someFolder` and `.someconfig` should be synced, but the README not and the own files/folders should be preserved.

```yaml
  - name: template-parent
    dst: .                                                          # explicitly tell to use root of project
    url: https://github.com/dfetch/template.git       
    src:                                                            # mark (multiple) desired files/folders
    - somefolder
    - .someconfig
    clear: false                                                    # don't clear dest folder before update
```

I'm open to any suggestions!
