### ISSUE TITLE
SVN: dfetch check broken when using a branch

### ISSUE THREAD

**Issue by sach-edna** [dfetch-org/dfetch#383]
When checking a svn entry in the dfetch file there is an issue with the revision number.
It seems to be ignored when checking.
The last revision number is checked instead.
The files do exist at this revision number, but they are numbered at a different revision, which causes the following.
### manifest
```yaml
manifest:
  version: '0.0'

  remotes:
  - name: testproject
    url-base: http://svn.local/testproject

  projects:
  - name: Resources
    revision: '681'
    remote: testproject
    dst: Quality/Resources
    branch: test_memory_parser
    repo-path: Resources
```
### output
```sh
>>>svn info http://svn.local/testproject/Resources/test_memory_parser<<< returned 1:
svn: warning: W170000: URL 'http://svn.local/testproject/Resources/test_memory_parser' non-existent in revision 700

svn: E200009: Could not display info for all targets because some targets don't exist
```
I would expect the behavior to be that `dfetch check` checks the svn repository at the specified revision and gives feedback on that one.
