### ISSUE TITLE
Condition for uploading codacy report action is incorrect

### ISSUE THREAD

**Issue by jgeudens** [dfetch-org/dfetch#558]
It is possible that the condition for uploading the codacy report is not working correctly?

It seems that the latest action runs always skip the upload step: https://github.com/dfetch-org/dfetch/actions/runs/7126301482/job/19403900008

### Code
```yaml
        env:
          secrets.CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        if: "${{ (!!env.CODACY_PROJECT_TOKEN) }}"
```
https://github.com/dfetch-org/dfetch/blob/3f55e9d173fa7413e4a11000e957af082bc189d4/.github/workflows/test.yml#L45C12-L45C12

I think that the env variable should drop the `secret.` prefix.

```yaml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        if: "${{ (!!env.CODACY_PROJECT_TOKEN) }}"
```
