### ISSUE TITLE
Add possibilty to exclude / ignore files

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#571]
Sometimes  a project has some large subfolder you want to ignore, or certain files that are not interesting.
Add a new field to `project` in manifest to list folders/files to be ignored:

```yaml

  projects:
  - name: SomeFolderWithStuff
    repo-path: some-git
    ignore:
        - LargeFolderWithTests/
        - uninteresting.txt
        - LargeFolderWithTests/file_in_subfolder.txt
```

The file paths should be relative to the `src:` directory

- `url-base`:`repo-path`:`src` + *`ignore`*
- `url`:`src` + *`ignore`*

Implementation would be different per vcs:
- In SVN use the `--ignore` flag
- In Git ignore the folders using the `sparse-checkout` if possible?
