### ISSUE TITLE
Only sha of submodule instead of tag during dfetch import

### ISSUE THREAD

**Issue by jgeudens** [dfetch-org/dfetch#61]
I have used the dfetch import command to generate a manifest of my git submodules. One of my submodules was pinned to a tag. The generated manifest contains seemingly correct information. A tag is just a label to a specific revision on the master (in this case). So it is reasonable that the branch option isn't added because the default is master. And the correct specific revision is mentioned.

```
  projects:
  - name: libraries/muparser
    revision: 207d5b77c05c9111ff51ab91082701221220c477
    remote: https---github-com-beltoforion
    dst: libraries/muparser
    repo-path: muparser.git
```

But when using dfetch update, another file is generated. This file mentions the specific tag name and revision.

Content of `.dfetch_data.yaml`
```
dfetch:
  branch: v2.3.2
  last_fetch: 20/01/2021, 22:22:01
  remote_url: https://github.com/beltoforion/muparser.git
  revision: 207d5b77c05c9111ff51ab91082701221220c477
```

For me, it would make sense that the originally generated manifest also specifies the correct tag name as branch option. When using an external library, one would normally update to the next tag (release) and not follow every commit on master.

PS: the `.dfetch_data.yaml` doesn't seem to be mentioned in the documentation. Is this file an auto-generated file that can be ignored or a configuration file that should be added to the repo?
