### ISSUE TITLE
Non destructive file update in root and sub directories

### ISSUE THREAD

**Issue by deminngi** [dfetch-org/dfetch#616]
When using **`dfetch update`** I would like to update a single file or a set of files in a cloned local project root or subdirectory, without deleting the entire content in it, because I would like to preserve some artefacts that were built before.

That means I would like something like:

```yaml
projects:
  - name: get-scripts-into-root
    repo-path: git.dev/demo.git
    src: '*.sh'
    dst: /
  - name: get-scripts-into-sub
    repo-path: git.dev/demo.git
    src: '*.sh*'
    dst: /sub
```

I understand that **`dst`** accepts only directories, but an update flag may solve my problem.

For example:

```bash
dfetch update --non-destructive
```

The above flag would works for:
 
- single file(s) in a root directory
- single file(s) in a sub directory
