### ISSUE TITLE
SVN: Fetching single src file to dst results in dst name used for file

### ISSUE THREAD

**Issue by spoorcc** [dfetch-org/dfetch#641]
Fetching below manifest:

```yaml
  - name: cutter-readme
    vcs: svn
    tag: 1.1.7
    dst: ext/cutter-svn-tag
    url: svn://svn.code.sf.net/p/cutter/svn/cutter
    src: README
```

Results in:

![image](https://github.com/user-attachments/assets/3405ea64-1c48-493c-b87d-a7a16537f281)
