### ISSUE TITLE
Child manifest only suggests repo-path

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#683]
When  a component "MyComponent" has this as manifest for needed dependency:

```yaml
manifest:
  version: 0.0

  remotes:
  - name: github
    url-base: https://github.com/

  projects:
  - name: Jsmn
    dst: Core/Jsmn
    repo-path: zserge/jsmn.git
    ignore:
    - example
    - test
    - .clang-format
    - .travis.yml
    revision: 25647e692c7906b96ffd2b05ca54c097948e879c
```

and that component is fetched the output is:

```console
"MyComponent" depends on the following project(s) which are not part of your manifest:
(found in modules/JsonParse/dfetch.yaml)

-   name: Jsmn
    revision: 25647e692c7906b96ffd2b05ca54c097948e879c
    repo-path: zserge/jsmn.git
```

But this does not give the full url, so it is hard to guess where it should be retrieved. Either also show the required `remote` or upgrade the `repo-path` to the full url
