### ISSUE TITLE
Overlapping path check too strict

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#684]
Given this manifest:

```yaml
 remotes:
  - name: git-mycompany
    url-base: git@git.mycompany.eu:mycompany/

  projects:
  - name: JsonParse
    dst: modules/JsonParse
    repo-path: modules/string
    src: Core/JsonParse

  - name: Json
    dst: modules/Json
    repo-path: modules/string
    src: Core/Json
```

The console shows:
```
Dfetch (0.9.1)
Multiple manifests found, using dfetch.yaml
  JsonParse           : Fetched feature/single-jsmn - b6bb2b9b23411271e246c7979d4c5879e334b333
  Json                : Skipping due to overlapping destination: "modules/Json"
There is already a project in "modules/Json" or one of its subfolders!
Each destination must be unique and not overlapping.
```

This is wrong, it should not look at overlapping names
