### ISSUE TITLE
Git: Auto-select HEAD branch as default branch

### ISSUE THREAD

**Issue by sach-edna** [dfetch-org/dfetch#689]
Trying to get data from the dfetch repo itself, using 
```yml
manifest:
  version: 0.0                                            # DFetch Module syntax version

  remotes:                                                # declare common sources in one place
  - name: github
    url-base: https://github.com/

  projects:
  - name: dfetch-devcontainer
    dst: .devcontainer
    repo-path: dfetch-org/dfetch
    src: .devcontainer
```
does not work:
```
stderr:

  dfetch-devcontainer : wanted (), but not available at the upstream.
```
adding `branch:main` does work, which indicates to me main is not seen as default branch when master is missing.
