### ISSUE TITLE
svn branches or tags prefix required

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#88]
Given an svn project, the branch must include either the `branches` or `tags` prefix. Below file works. 
This however feels a little bit clunky. 

```yaml
manifest:
  version: 0.0

  remotes:
  - name: github
    url-base: https://github.com/cpputest/cpputest

  projects:
  - name: cpputest-tags
    branch: tags/v3.7                     # <<< tags explicit
    vcs: svn

  - name: cpputest-branches
    branch: branches/gh-pages            # <<< branches explicit
    vcs: svn
```
