### ISSUE TITLE
Use manifests found in projects

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#99]
Given a project:

```
MyProject/

    main.c
    dfetch.yaml
```

With the following manifest:

```yaml
dfetch:
    version: 0.0
    projects:
         name: SomeProject
         dst: ThirdParty/SomeProject
```

Where the other project also has a manifest for its own dependencies:
```
SomeProject/
    some_project.c
    dfetch.yaml
```

With the following manifest:
```yaml
dfetch:
    version: 0.0
    projects:
         name: SomeOtherProject
         dst: ../SomeOtherProject
```

Referring to the following code:
```
SomeOtherProject/
    some_other_project.c
```

When `dfetch update` is done, this should result in:

```
MyProject/

    main.c
    dfetch.yaml

    ThirdParty/
          SomeProject/
              some_project.c
              dfetch.yaml

          SomeOtherProject/
              some_other_project.c
```

# Version/name clashes
- To prevent name clashes, use scoping, imported project are prefixed with the projects name that imported them. In the top example `SomeOtherProject` is named `SomeProject/SomeOtherProject`.
- Let the toplevel manifest always have priority: If toplevel has a project with the destination, warn and ignore the 'imported' project
- If two imported manifests have clashing destinations: stop and let the user decide
- Provide a flag for disabling manifest importing
